### ISSUE TITLE
Authorization with Bearer Tokens

### ISSUE THREAD

**Issue by CorneliusOsei2** [TechElevateGH/healthy-cup-backend#6]

**Comment by CorneliusOsei2** [comment]
https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/

**Comment by TONYOG12** [comment]
I was thinking of refactoring the security.create_token function to the create_access_token method from flask-jwt-extended module in order to implicitly refresh the access token with cookies. thoughts?

**Comment by CorneliusOsei2** [comment]
Sounds good to me. I did not use jwt-extended from the start since I just wanted access token then. Also I did not see sooo much usage of jwt-extended and thought implementing custom refresh tokens should be manageable. But sure if you think that's a good way around it, @TONYOG12
